spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tfg}
    username: ${SPRING_DATASOURCE_USERNAME:tfg}
    password: ${SPRING_DATASOURCE_PASSWORD:tfg}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      encoding: UTF-8
      mode: always
      continue-on-error: false
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:pepe11.perez91@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:dhvc hfet nieo afpr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  task:
    execution:
      pool:
        core-size: 4
        max-size: 10
        queue-capacity: 100
logging:
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
  level:
    root: INFO
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
properties:
  clientHost: ${PROPERTIES_CLIENTHOST:http://localhost:1234}
  jwtSecretKey: ${PROPERTIES_JWTSECRET:dev-secret}
  jwtValidity: ${PROPERTIES_JWTVALIDITY:7200}
  upload:
    path: ${PROPERTIES_UPLOAD_PATH:/tmp/uploads}
app:
  base:
    url: ${APP_BASE_URL:http://localhost:8080}
